[package]
name = "config_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg ={ version = "0.13.3", package = "config" }
serde = "1.0"
serde_derive = "1.0"