[package]
name = "gst_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.18.1"
gst = { version = "0.21", package = "gstreamer" }